# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/timing.xdc

# IP: ip/icache_data_bram/icache_data_bram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==icache_data_bram || ORIG_REF_NAME==icache_data_bram} -quiet] -quiet

# IP: ip/inst_mem_3/inst_mem.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inst_mem || ORIG_REF_NAME==inst_mem} -quiet] -quiet

# IP: ip/data_mem_2/data_mem.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_mem || ORIG_REF_NAME==data_mem} -quiet] -quiet
