# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/riscv32_pipeline_v1/riscv32_pipeline.runs/synth_1_copy_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1_copy_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/riscv32_pipeline_v1/riscv32_pipeline.cache/wt [current_project]
set_property parent.project_path D:/riscv32_pipeline_v1/riscv32_pipeline.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/riscv32_pipeline_v1/riscv32_pipeline.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files D:/riscv32_pipeline_v1/inst.coe
add_files D:/riscv32_pipeline_v1/coremark.coe
add_files D:/riscv32_pipeline_v1/riscv32_pipeline.ip_user_files/mem_init_files/coremark_uart.coe
add_files D:/riscv32_pipeline_v1/riscv32_pipeline.ip_user_files/mem_init_files/coremark_v2.coe
add_files D:/riscv32_pipeline_v1/riscv32_pipeline.ip_user_files/mem_init_files/coremark_v3.coe
add_files D:/riscv32_pipeline_v1/riscv32_pipeline.ip_user_files/mem_init_files/coremark_v3_1.coe
add_files D:/riscv32_pipeline_v1/riscv32_pipeline.ip_user_files/mem_init_files/coremark_v4.coe
add_files D:/riscv32_pipeline_v1/riscv32_pipeline.ip_user_files/mem_init_files/coremark_v4_1.coe
add_files D:/riscv32_pipeline_v1/riscv32_pipeline.ip_user_files/mem_init_files/coremark_v4_2.coe
add_files D:/riscv32_pipeline_v1/riscv32_pipeline.ip_user_files/mem_init_files/coremark_v4_3.coe
add_files D:/riscv32_pipeline_v1/riscv32_pipeline.ip_user_files/mem_init_files/coremark_v5.coe
read_verilog D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/param.v
set_property file_type "Verilog Header" [get_files D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/param.v]
set_property is_global_include true [get_files D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/param.v]
read_verilog -library xil_defaultlib {
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/basic/alu/ALU.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/basic/ctrl/ALUope.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/basic/pc/BHT.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/basic/pc/BTB.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/IO/BUS/BUS.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/basic/ctrl/BranchCTRL.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/basic/pc/BranchPredictor.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/basic/alu/COMP.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/basic/ctrl/CTRL.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/combine/EX.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/combine/EX_IF.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/combine/EX_MEM.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/basic/ctrl/ExceptionCTRL.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/basic/ctrl/ForwardingUnit.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/combine/ID.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/combine/ID_EX.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/combine/IF.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/combine/IF_ID.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/basic/ctrl/InstDivider.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/combine/MEM.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/combine/MEM_WB.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/basic/pc/NPC.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/combine/WB.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/IO/buffer/buffer.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/basic/mem/dataMem.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/IO/clk/deviceCLK.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/basic/alu/immGen.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/IO/interface_LED_SWITCH/inputCtrl_LED.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/IO/interface_NUMLED/inputCtrl_NUMLED.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/IO/interface_RAM/inputCtrl_RAM.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/basic/mem/instMem.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/IO/interface_LED_SWITCH/interface_LED_SWITCH.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/IO/interface_NUMLED/interface_NUMLED.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/IO/interface_RAM/interface_RAM.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/miniRV.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/IO/interface_RAM/outputCtrl_RAM.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/IO/interface_LED_SWITCH/outputCtrl_Switch.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/basic/mem/regFIle.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/top.v
  {D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/M extension/divider.v}
  {D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/M extension/multiplier.v}
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/basic/pc/PC.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/basic/clk/cpuclk.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/interface_UART.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/interface_Timer.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/cache/dCache_Wrapper.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/cache/iCache_Wrapper.v
  D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/new/cache/cache.v
}
read_ip -quiet D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/ip/icache_data_bram/icache_data_bram.xci
set_property used_in_implementation false [get_files -all d:/riscv32_pipeline_v1/riscv32_pipeline.gen/sources_1/ip/icache_data_bram/icache_data_bram_ooc.xdc]

read_ip -quiet D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/ip/inst_mem_3/inst_mem.xci
set_property used_in_implementation false [get_files -all d:/riscv32_pipeline_v1/riscv32_pipeline.gen/sources_1/ip/inst_mem_3/inst_mem_ooc.xdc]

read_ip -quiet D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/ip/data_mem_2/data_mem.xci
set_property used_in_implementation false [get_files -all d:/riscv32_pipeline_v1/riscv32_pipeline.gen/sources_1/ip/data_mem_2/data_mem_ooc.xdc]

read_ip -quiet D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/ip/cpuclk_2/cpuclk.xci
set_property used_in_implementation false [get_files -all d:/riscv32_pipeline_v1/riscv32_pipeline.gen/sources_1/ip/cpuclk_2/cpuclk_board.xdc]
set_property used_in_implementation false [get_files -all d:/riscv32_pipeline_v1/riscv32_pipeline.gen/sources_1/ip/cpuclk_2/cpuclk.xdc]
set_property used_in_implementation false [get_files -all d:/riscv32_pipeline_v1/riscv32_pipeline.gen/sources_1/ip/cpuclk_2/cpuclk_ooc.xdc]

read_ip -quiet D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/sources_1/ip/dcache_data_bram/dcache_data_bram.xci
set_property used_in_implementation false [get_files -all d:/riscv32_pipeline_v1/riscv32_pipeline.gen/sources_1/ip/dcache_data_bram/dcache_data_bram_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/constrs_1/new/timing.xdc
set_property used_in_implementation false [get_files D:/riscv32_pipeline_v1/riscv32_pipeline.srcs/constrs_1/new/timing.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7z020clg400-2 -directive AreaOptimized_high -control_set_opt_threshold 1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_copy_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1_copy_1" END { }
