open_project D:/riscv32_pipeline_cache/riscv32_pipeline.xpr
current_run -implementation [get_runs impl_trial_netdelay_high]
launch_runs impl_trial_netdelay_high -to_step write_bitstream -jobs 8
wait_on_run impl_trial_netdelay_high
set status [get_property STATUS [get_runs impl_trial_netdelay_high]]
puts "NETDELAY_STATUS=$status"
open_run impl_trial_netdelay_high
report_timing_summary -file D:/riscv32_pipeline_cache/report_artifacts/impl_strategy_trials/impl_trial_netdelay_high_timing_after_bitgen.rpt
report_utilization -file D:/riscv32_pipeline_cache/report_artifacts/impl_strategy_trials/impl_trial_netdelay_high_util_after_bitgen.rpt
exit
