# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/riscv32_pipeline_cache/riscv32_pipeline.srcs/sources_1/ip/dcache_data_bram/dcache_data_bram.xci
# IP: The module: 'dcache_data_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/riscv32_pipeline_cache/riscv32_pipeline.gen/sources_1/ip/dcache_data_bram/dcache_data_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcache_data_bram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/riscv32_pipeline_cache/riscv32_pipeline.srcs/sources_1/ip/dcache_data_bram/dcache_data_bram.xci
# IP: The module: 'dcache_data_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/riscv32_pipeline_cache/riscv32_pipeline.gen/sources_1/ip/dcache_data_bram/dcache_data_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcache_data_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
